In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df = pd.read_csv('train.txt',sep = ';',names = ['text','emotion'])
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [27]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [28]:
df['emotion'].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

df['emotion'] = encode.fit_transform(df['emotion'])

In [30]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

# data cleaning!!

In [31]:
# lowercasing every text-
df['text']=df['text'].apply(lambda x: x.lower())
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [32]:
# remove punctuation !!
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))


df['text'] = df['text'].apply(remove_punc)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [33]:
# remove digit !!
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [34]:
# remove url & links !!
import re

def remove_urls(text):
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['text']=df['text'].apply(remove_urls)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [35]:
# remove emojis from text !!
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [36]:
# remove stopwords !!
import nltk


from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [37]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [38]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [39]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [55]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

df['text'] = df['text'].apply(remove)

In [56]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [57]:
# bag of words!
# CountVectorizer & TfidfVectorizer se hum data cleaning ke sare process kr sakte hai!!
from sklearn.feature_extraction.text import CountVectorizer

doc=[
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document'
]

vectorizer=CountVectorizer(ngram_range=(2,2))
X= vectorizer.fit_transform(doc)

print('vocabulary :',vectorizer.get_feature_names_out())
print(X.toarray())

vocabulary : ['and this' 'document is' 'first document' 'is the' 'is this'
 'second document' 'the first' 'the second' 'the third' 'third one'
 'this document' 'this is' 'this the']
[[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]

In [58]:
# TF-IDF  [Term Frequency & Inverse Document Frequency]

from sklearn.feature_extraction.text import TfidfVectorizer

doc=[
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document'
]

vectorizer=TfidfVectorizer()
X= vectorizer.fit_transform(doc)

print('vocabulary :',vectorizer.get_feature_names_out())
print(X.toarray().round(2))

vocabulary : ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.   0.47 0.58 0.38 0.   0.   0.38 0.   0.38]
 [0.   0.69 0.   0.28 0.   0.54 0.28 0.   0.28]
 [0.51 0.   0.   0.27 0.51 0.   0.27 0.51 0.27]
 [0.   0.47 0.58 0.38 0.   0.   0.38 0.   0.38]]

In [74]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split( df['text'], df['emotion'] ,test_size=0.2,random_state=42)

In [75]:
df.shape

(16000, 2)

In [76]:
X_train.shape

(12800,)

In [77]:
X_test.shape

(3200,)

In [83]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

bow_vectorizer = CountVectorizer()
tfidf_vectorizer = TfidfVectorizer()

X_train_BOW = bow_vectorizer.fit_transform(X_train)
X_test_BOW = bow_vectorizer.transform(X_test)

X_train_TFIDF = tfidf_vectorizer.fit_transform(X_train)
X_test_TFIDF = tfidf_vectorizer.transform(X_test)

# MULTINOMINAL NAIVE BAYES

In [84]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

mnb_model = MultinomialNB()
mnb_model.fit(X_train_BOW,y_train)      #Multinominal naive bayes model made by dataset using BOW

MultinomialNB()

In [87]:
bow_predict = mnb_model.predict(X_test_BOW)
bow_predict

array([4, 2, 4, ..., 2, 2, 4])

In [88]:
accuracy_score(y_test,bow_predict)

0.7678125

In [89]:
mnb_model.fit(X_train_TFIDF,y_train)         #Multinominal naive bayes model made by dataset using TFIDF

MultinomialNB()

In [91]:
tfidf_predict = mnb_model.predict(X_test_TFIDF)
tfidf_predict

array([4, 2, 4, ..., 2, 2, 4])

In [92]:
accuracy_score(y_test,tfidf_predict)

0.6609375

# Logestic Regression

In [93]:
from sklearn.linear_model import LogisticRegression

In [109]:
lrmodel_bow = LogisticRegression()
lrmodel_bow.fit(X_train_BOW,y_train)

LogisticRegression()

In [110]:
bow_predict = lrmodel_bow.predict(X_test_BOW)
bow_predict

array([4, 2, 4, ..., 2, 2, 4])

In [111]:
accuracy_score(y_test,bow_predict)

0.88875

In [106]:
lrmodel_tfidf = LogisticRegression()
lrmodel_tfidf.fit(X_train_TFIDF,y_train)

LogisticRegression()

In [107]:
tfidf_predict = lrmodel_tfidf.predict(X_test_TFIDF)
tfidf_predict

array([4, 2, 4, ..., 2, 2, 4])

In [108]:
accuracy_score(y_test,tfidf_predict)

0.8615625